# Configuration Dokploy optimisée
build:
  dockerfile: Dockerfile.ultra-minimal
  timeout: 600
  memory: 1024
  
deploy:
  replicas: 1
  resources:
    limits:
      memory: 512M
    reservations:
      memory: 256M
      
environment:
  NODE_OPTIONS: "--max-old-space-size=256"
  NEXT_TELEMETRY_DISABLED: "1"
  
health_check:
  test: ["CMD", "wget", "-q", "--spider", "http://localhost:3000/api/health"]
  interval: 30s
  timeout: 10s
  retries: 3