version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dokploy-absolute
    ports:
      - "${PORT:-3000}:3000"
    environment:
      # FORCER absolument le mode production
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      
      # Configuration MongoDB
      - MONGODB_URI=${MONGODB_URI:-mongodb://localhost:27017/ezia}
      
      # Tokens API
      - HF_TOKEN=${HF_TOKEN}
      - DEFAULT_HF_TOKEN=${DEFAULT_HF_TOKEN}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      
      # Secrets
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-your-nextauth-secret}
      
      # URLs publiques pour HTTPS
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-https://ezia.ai}
      - NEXT_PUBLIC_ASSET_PREFIX=${NEXT_PUBLIC_ASSET_PREFIX:-https://ezia.ai}
      
    restart: unless-stopped
    
    # IMPORTANT: NE PAS mettre de "command" ici
    # Dokploy ne doit pas pouvoir override notre ENTRYPOINT
    
    # Healthcheck pour s'assurer que le serveur répond
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s