services:
  ezia:
    build:
      context: .
      dockerfile: Dockerfile.dokploy
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped