version: '3.8'

services:
  ezia:
    build:
      context: .
      dockerfile: Dockerfile.dokploy
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
      - HF_TOKEN=${HF_TOKEN}
      - DEFAULT_HF_TOKEN=${DEFAULT_HF_TOKEN}
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}
      - NEXT_APP_API_URL=${NEXT_APP_API_URL}
    volumes:
      - ezia-data:/app/.data
    restart: unless-stopped

volumes:
  ezia-data: