services:
  ezia:
    build:
      context: .
      dockerfile: Dockerfile.fast
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NODE_OPTIONS=--max-old-space-size=1024
    restart: unless-stopped