# docker-compose override pour injecter les secrets en production
# À utiliser avec: docker-compose -f docker-compose.yml -f docker-compose.secrets.yml up -d

version: '3.8'

services:
  app:
    environment:
      # MongoDB
      - MONGODB_URI=${MONGODB_URI}

      # HuggingFace
      - HF_TOKEN=${HF_TOKEN}
      - DEFAULT_HF_TOKEN=${DEFAULT_HF_TOKEN}

      # Mistral AI
      - MISTRAL_API_KEY=${MISTRAL_API_KEY}

      # Auth
      - JWT_SECRET=${JWT_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}

      # Feature Flags
      - DISABLE_ECOSYSTEM_FEATURE=${DISABLE_ECOSYSTEM_FEATURE}
      - NEXT_PUBLIC_DISABLE_ECOSYSTEM_FEATURE=${NEXT_PUBLIC_DISABLE_ECOSYSTEM_FEATURE}

      # Brevo Email Service (CRITIQUE POUR WEBINAIRE)
      - BREVO_API_KEY=${BREVO_API_KEY}
      - BREVO_LIST_ID_STARTUP=${BREVO_LIST_ID_STARTUP}
      - BREVO_LIST_ID_ENTERPRISE=${BREVO_LIST_ID_ENTERPRISE}
      - BREVO_TEMPLATE_WAITLIST_STARTUP=${BREVO_TEMPLATE_WAITLIST_STARTUP}
      - BREVO_TEMPLATE_WAITLIST_ENTERPRISE=${BREVO_TEMPLATE_WAITLIST_ENTERPRISE}
      - BREVO_SENDER_EMAIL=${BREVO_SENDER_EMAIL}
      - ADMIN_NOTIFICATION_EMAIL=${ADMIN_NOTIFICATION_EMAIL}

      # Analytics
      - NEXT_PUBLIC_GA_MEASUREMENT_ID=${NEXT_PUBLIC_GA_MEASUREMENT_ID}

      # HuggingFace Spaces
      - DEEPSITE_HF_URL=${DEEPSITE_HF_URL}
      - DEEPSITE_SPACE_ID=${DEEPSITE_SPACE_ID}

      # Next.js Config
      - NEXT_APP_API_URL=${NEXT_APP_API_URL}
      - NEXT_TELEMETRY_DISABLED=${NEXT_TELEMETRY_DISABLED}
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL}

      # Quotas
      - FREE_MONTHLY_WEBSITES=${FREE_MONTHLY_WEBSITES}
      - FREE_MONTHLY_ANALYSES=${FREE_MONTHLY_ANALYSES}
      - FREE_MONTHLY_CONVERSATIONS=${FREE_MONTHLY_CONVERSATIONS}

      # Redirect
      - NEXT_PUBLIC_REDIRECT_URL=${NEXT_PUBLIC_REDIRECT_URL}
