services:
  ezia:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./:/app
    command: sh -c "npm install --production && npm start"
    restart: unless-stopped